server:
  port: 8080

spring:
  application:
    name: com.kb.health
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:coding_test;MODE=Mysql;DATABASE_TO_LOWER=TRUE
#    username: test
#    password: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coding_test?serverTimezone=Asia/Seoul
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true


logging:
  level:
    root: info
    web: trace
    sql: trace


